# Consultar todas las bases de datos dentro del datalake
 - Conexion al Datalake mediante .env
 - Montar puntero
 - Consultar librerias
 - Exploracion
 #### --- jcx@quantarmy.com - quantarmy.com | pythonparatrading.com

In [39]:
from arcticdb import Arctic
import pandas as pd
from dotenv import load_dotenv
from os import getenv

In [40]:
dotenv_path = '/root/.env'
load_dotenv(dotenv_path)

endpoint = getenv("ENDPOINT")
db = getenv("DB")
access_key = getenv("ACCESS_KEY")
secret_key = getenv("SECRET_KEY")

ac = Arctic(f's3s://{endpoint}:{db}?access={access_key}&secret={secret_key}')

In [93]:
metadata = ac.get_library('meta.stable')
metadata = metadata.read('NYSE').data
metadata[metadata['qa_ticker'] == 'JPM.US'].T

                           JPM.US
code                          JPM
name          JPMorgan Chase & Co
exchange                     NYSE
type                 Common Stock
currency                US Dollar
country                        US
qa_ticker                  JPM.US
ipo                    1978-10-06
fiscal                   December
sector         Financial Services
industry        Banks-Diversified
gsector                Financials
ggroup                      Banks
gindustry                   Banks
gsubindustry    Diversified Banks
full_workers             300066.0
mkcap              426672160768.0
ebdita                        NaN
per                        9.4418
peg                        1.1661
target                     169.34
outstanding          2906089984.0
insiders                    0.885
institutions               71.106

In [94]:
price = ac.get_library('prices.stocks.us.stable')
price.read('JPM.US').data

                open      high       low     close       volume
date
1984-11-05   10.3334   10.5834   10.3334   10.3334     79800.00
1984-11-06   10.5417   10.7084   10.5417   10.5417    421799.99
1984-11-07   10.5000   10.6667   10.5000   10.5000    310199.99
1984-11-08   10.5000   10.6250   10.5000   10.5000    267599.99
1984-11-09   10.5417   10.6250   10.5417   10.5417    199799.99
...              ...       ...       ...       ...          ...
2023-08-29  147.7100  148.8500  147.1800  148.7600   6337000.00
2023-08-30  148.6200  149.1500  147.1900  148.1600   6277300.00
2023-08-31  148.2600  148.3500  145.9600  146.3300  10933900.00
2023-09-01  146.0900  148.0800  145.7000  146.8200   7902100.00
2023-09-05  147.1600  148.2099  145.0100  145.2000   7774061.00

[9786 rows x 5 columns]

In [92]:
splits = ac.get_library('splits.stocks.us.stable')
splits.read('JPM.US').data

            split
date
1982-04-16    1.5
1984-04-16    1.5
1998-06-15    2.0
2000-06-12    1.5

In [96]:
divs = ac.get_library('divs.stocks.us.stable')
divs.read('JPM.US').data

,declarationDate,recordDate,paymentDate,period,value,unadjustedValue,currency
date,,,,,,,
1984-12-10,None,None,None,None,0.19667,0.59001,USD
1985-03-11,None,None,None,None,0.20667,0.62001,USD
1985-06-10,None,None,None,None,0.20667,0.62001,USD
1985-09-09,None,None,None,None,0.20667,0.62001,USD
1985-12-09,None,None,None,None,0.20667,0.62001,USD
...,...,...,...,...,...,...,...
2022-07-05,None,2022-07-06,2022-07-31,Quarterly,1.00000,1.00000,USD
2022-10-05,2022-09-20,2022-10-06,2022-10-31,Quarterly,1.00000,1.00000,USD
2023-01-05,2022-12-13,2023-01-06,2023-01-31,Quarterly,1.00000,1.00000,USD
2023-04-05,2023-03-21,2023-04-06,2023-04-30,Quarterly,1.00000,1.00000,USD
2023-07-05,2023-05-15,2023-07-06,2023-07-31,Quarterly,1.00000,1.00000,USD

In [97]:
fundamental = ac.get_library('fundamental.stocks.us.stable')
fundamental.read('JPM.US').data.T

                                        0
MarketCapitalization         417663254528
MarketCapitalizationMln       417663.2545
EBITDA                               None
PERatio                            9.2424
PEGRatio                           1.1661
WallStreetTargetPrice              169.62
BookValue                          98.109
DividendShare                           4
DividendYield                      0.0278
EarningsShare                       15.55
EPSEstimateCurrentYear              15.97
EPSEstimateNextYear                 14.72
EPSEstimateNextQuarter               3.45
EPSEstimateCurrentQuarter            3.99
MostRecentQuarter              2023-06-30
ProfitMargin                       0.3538
OperatingMarginTTM                 0.4198
ReturnOnAssetsTTM                  0.0124
ReturnOnEquityTTM                  0.1598
RevenueTTM                   135220002816
RevenuePerShareTTM                 45.697
QuarterlyRevenueGrowthYOY           0.206
GrossProfitTTM               122306000000
DilutedEpsTTM                       15.55
QuarterlyEarningsGrowthYOY          0.721
TrailingPE                         9.2424
ForwardPE                         10.3842
PriceSalesTTM                      3.1647
PriceBookMRQ                       1.5335
EnterpriseValue             -240760422400
EnterpriseValueRevenue                  0
EnterpriseValueEbitda                   0
Beta                               1.0958
52WeekHigh                         159.38
52WeekLow                          99.074
50DayMA                          150.4656
200DayMA                         139.9038
SharesShort                      19160644
SharesShortPriorMonth            18766194
ShortRatio                           2.09
ShortPercent                       0.0066
Rating                               4.08
TargetPrice                        162.75
StrongBuy                              10
Buy                                     7
Hold                                    8
Sell                                    0
StrongSell                              0
RatingDate                     2019-01-01
TotalEsg                            24.51
TotalEsgPercentile                  28.52
EnvironmentScore                     1.16
EnvironmentScorePercentile              3
SocialScore                         12.45
SocialScorePercentile                   3
GovernanceScore                       7.4
GovernanceScorePercentile               3
ControversyLevel                        3

In [102]:
news = ac.get_library('us.stocks.news.stable')
news.read('JPM.US').data.sort_index()

,title,content,link,tags,tag,polarity,neg,neu,pos
date,,,,,,,,,
2020-05-27T23:23:27+00:00,"Louis Moore Bacon Buys Ross, Bets on Corporate...","Louis Moore Bacon (Trades, Portfolio)'s Moore ...",https://finance.yahoo.com/news/louis-moore-bac...,"['CORPORATE BOND', 'CORPORATE BOND ETF', 'EQUI...",intrinsic value,0.994,0.017,0.905,0.078
2020-06-26T19:26:11+00:00,Fed to cap bank dividend payments after comple...,The Federal Reserve will bar big banks from in...,https://finance.yahoo.com/video/fed-stress-tes...,"['AKIKO FUJITA', 'CALVIN SCHNURE', 'DIVIDEND P...",dividend payments,0.922,0.065,0.863,0.072
2020-06-30T09:00:00+00:00,Coronavirus strikes down global M&amp;A as com...,By Joshua Franklin and Pamela Barbaglia\n\nNEW...,https://finance.yahoo.com/news/coronavirus-str...,"['BALANCE SHEET', 'BALANCE SHEETS', 'COMPANIES...",balance sheet,0.985,0.029,0.899,0.072
2020-09-30T20:15:20+00:00,Fed extends ban on share buybacks at big banks...,The Federal Reserve said Wednesday that it wil...,https://finance.yahoo.com/news/fed-extends-ban...,"['DIVIDEND PAYMENTS', 'FEDERAL RESERVE', 'LAEL...",dividend payments,0.76,0.083,0.815,0.102
2020-10-14T18:41:34+00:00,Big banks offer cautious optimism over economi...,Yahoo Finance's Brian Cheung joins Zack Guzman...,https://finance.yahoo.com/video/big-banks-offe...,"['BANK OF AMERICA', 'EARNINGS PER SHARE', 'EAR...",earnings per share,0.46,0.062,0.864,0.074
...,...,...,...,...,...,...,...,...,...
2023-03-23T14:27:02+00:00,JPMorgan (JPM) to Buy Investment Analytics Sof...,JPMorgan JPM has entered an agreement to acqui...,https://finance.yahoo.com/news/jpmorgan-jpm-bu...,"['DIGITAL SOLUTIONS', 'JPMORGAN', 'PRIVATE MAR...",zacks investment research,0.997,0.004,0.848,0.149
2023-03-23T21:45:09+00:00,JPMorgan Chase &amp; Co. (JPM) Stock Sinks As ...,JPMorgan Chase & Co. (JPM) closed the most rec...,https://finance.yahoo.com/news/jpmorgan-chase-...,"['ESTIMATE REVISIONS', 'JPMORGAN CHASE & CO', ...",zacks rank,0.99,0.014,0.893,0.093
2023-03-23T21:45:09+00:00,JPMorgan Chase &amp; Co. (JPM) Stock Sinks As ...,JPMorgan Chase & Co. (JPM) closed the most rec...,https://finance.yahoo.com/news/jpmorgan-chase-...,"['ESTIMATE REVISIONS', 'JPMORGAN CHASE & CO', ...",estimate revisions,0.99,0.014,0.893,0.093
2023-03-25T10:00:35+00:00,"SVB testimony, inflation update, and earnings-...","SVB hearings, major economic data, and some he...",https://finance.yahoo.com/video/svb-testimony-...,"['CAPITOL HILL', 'CONSUMER CONFIDENCE', 'FDIC'...",quarterly earnings,0.422,0.038,0.89,0.072
2023-03-27T13:37:01+00:00,"Company News for Mar 27, 2023","Shares of Block, Inc. (SQ) declined 1.9% follo...",https://finance.yahoo.com/news/company-news-ma...,"['BLOCK', 'HINDENBURG RESEARCH', 'INC', 'INCYT...",zacks investment research,0.968,0.057,0.739,0.204

In [106]:
income = ac.get_library('us.stocks.fundamental.income')
income.read('JPM.US').data

,filing_date,currency_symbol,researchDevelopment,effectOfAccountingCharges,incomeBeforeTax,minorityInterest,netIncome,sellingGeneralAdministrative,sellingAndMarketingExpenses,grossProfit,...,otherItems,incomeTaxExpense,totalRevenue,totalOperatingExpenses,costOfRevenue,totalOtherIncomeExpenseNet,discontinuedOperations,netIncomeFromContinuingOps,netIncomeApplicableToCommonShares,preferredStockAndOtherAdjustments
date,,,,,,,,,,,,,,,,,,,,,
1990-03-31,1990-03-31,USD,None,None,170100000.00,None,151700000.00,339100000.00,None,928100000.00,...,None,18400000.00,928100000.00,395900000.00,None,-1153900000.00,None,None,None,None
1990-06-30,1990-06-30,USD,None,None,130300000.00,None,113100000.00,338300000.00,None,848200000.00,...,None,17200000.00,848200000.00,379900000.00,None,-1097800000.00,None,None,None,None
1990-09-30,1990-09-30,USD,None,None,-27900000.00,None,-43700000.00,338700000.00,None,856100000.00,...,None,15800000.00,856100000.00,243500000.00,None,-1127500000.00,None,None,None,None
1990-12-31,1990-12-31,USD,None,None,73900000.00,None,70100000.00,319200000.00,None,874200000.00,...,None,3800000.00,874200000.00,280400000.00,None,-1080700000.00,None,None,None,None
1991-03-31,1991-03-31,USD,None,None,74900000.00,None,87000000.00,342900000.00,None,866200000.00,...,None,-12100000.00,866200000.00,123400000.00,None,-914700000.00,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-06-30,2022-08-03,USD,None,None,10865000000.00,None,8649000000.00,4845000000.00,881000000.00,27210000000.00,...,None,2216000000.00,30715000000.00,-18749000000.00,3505000000.00,2243000000.00,None,8649000000.00,8195000000.00,None
2022-09-30,2022-11-03,USD,None,None,12001000000.00,None,9737000000.00,4847000000.00,1017000000.00,29188000000.00,...,None,2264000000.00,32716000000.00,-19178000000.00,3528000000.00,2253000000.00,None,9737000000.00,9255000000.00,None
2022-12-31,2023-02-21,USD,None,None,13237000000.00,None,11008000000.00,4908000000.00,1093000000.00,32259000000.00,...,None,2229000000.00,34547000000.00,-19022000000.00,None,2082000000.00,None,11008000000.00,10597000000.00,None
2023-03-31,2023-05-03,USD,None,None,15967000000.00,None,12622000000.00,4632000000.00,1045000000.00,35050000000.00,...,None,3345000000.00,38349000000.00,-20107000000.00,3299000000.00,-16293000000.00,None,12622000000.00,12193000000.00,None
2023-06-30,2023-08-03,USD,None,None,17586000000.00,None,14472000000.00,11216000000.00,1122000000.00,37970000000.00,...,None,3114000000.00,41307000000.00,-3856000000.00,3337000000.00,-19865000000.00,None,14472000000.00,14011000000.00,None

In [107]:
income.read('JPM.US').data.columns

Index(['filing_date', 'currency_symbol', 'researchDevelopment',
       'effectOfAccountingCharges', 'incomeBeforeTax', 'minorityInterest',
       'netIncome', 'sellingGeneralAdministrative',
       'sellingAndMarketingExpenses', 'grossProfit', 'reconciledDepreciation',
       'ebit', 'ebitda', 'depreciationAndAmortization',
       'nonOperatingIncomeNetOther', 'operatingIncome',
       'otherOperatingExpenses', 'interestExpense', 'taxProvision',
       'interestIncome', 'netInterestIncome', 'extraordinaryItems',
       'nonRecurring', 'otherItems', 'incomeTaxExpense', 'totalRevenue',
       'totalOperatingExpenses', 'costOfRevenue', 'totalOtherIncomeExpenseNet',
       'discontinuedOperations', 'netIncomeFromContinuingOps',
       'netIncomeApplicableToCommonShares',
       'preferredStockAndOtherAdjustments'],
      dtype='object')

In [108]:
cashflow = ac.get_library('us.stocks.fundamental.cashflow')
cashflow.read('JPM.US').data

,filing_date,currency_symbol,investments,changeToLiabilities,totalCashflowsFromInvestingActivities,netBorrowings,totalCashFromFinancingActivities,changeToOperatingActivities,netIncome,changeInCash,...,changeToNetincome,capitalExpenditures,changeReceivables,cashFlowsOtherOperating,exchangeRateChanges,cashAndCashEquivalentsChanges,changeInWorkingCapital,stockBasedCompensation,otherNonCashItems,freeCashFlow
date,,,,,,,,,,,,,,,,,,,,,
1990-03-31,1990-03-31,USD,None,None,None,None,2508000000.00,None,151700000.00,-540000000.00,...,None,0,None,None,None,None,-55000000.00,None,239300000.00,390000000.00
1990-06-30,1990-06-30,USD,None,None,None,None,525000000.00,None,113100000.00,923000000.00,...,None,0,None,None,None,None,-234000000.00,None,-942100000.00,-1007000000.00
1990-09-30,1990-09-30,USD,None,None,None,None,-778000000.00,None,-43700000.00,-418000000.00,...,None,0,None,None,None,None,-79000000.00,None,1086700000.00,1030000000.00
1990-12-31,1990-12-31,USD,None,None,None,None,-999000000.00,None,70100000.00,625000000.00,...,None,0,None,None,None,None,339000000.00,None,-273100000.00,196000000.00
1991-03-31,1991-03-31,USD,None,None,None,None,-165000000.00,None,87000000.00,-1919000000.00,...,None,0,None,None,None,None,-111000000.00,None,-817000000.00,-784000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-06-30,2022-08-03,USD,-2030000000.00,22249000000.00,-53203000000.00,12633000000.00,-83802000000.00,-238000000.00,8649000000.00,-85272000000.00,...,5515000000.00,0,6668000000.00,21148000000.00,None,-70987000000.00,50065000000.00,None,6871000000.00,66018000000.00
2022-09-30,2022-11-03,USD,70621000000.00,25257000000.00,39522000000.00,18481000000.00,-32883000000.00,18088000000.00,9737000000.00,-25073000000.00,...,5975000000.00,0,1430000000.00,-62374000000.00,None,-11565000000.00,-35687000000.00,None,7344000000.00,-18204000000.00
2022-12-31,2023-02-21,USD,-14284000000.00,-33271000000.00,-51530000000.00,-40214000000.00,-142344000000.00,None,11008000000.00,-76953000000.00,...,6374000000.00,0,18651000000.00,96789000000.00,None,-92652000000.00,82169000000.00,None,5657000000.00,101222000000.00
2023-03-31,2023-05-03,USD,32632000000.00,-35107000000.00,23794000000.00,34425000000.00,64557000000.00,None,12622000000.00,-21234000000.00,...,2710000000.00,0,9823000000.00,-102938000000.00,None,-22890000000.00,-128222000000.00,None,3316000000.00,-111241000000.00
2023-06-30,2023-08-03,USD,27611000000.00,27533000000.00,-18243000000.00,13384000000.00,-49915000000.00,None,14472000000.00,-50877000000.00,...,1298000000.00,0,6284000000.00,-31229000000.00,None,-49293000000.00,2588000000.00,187000000.00,2743000000.00,18865000000.00

In [110]:
cashflow.read('JPM.US').data.columns

Index(['filing_date', 'currency_symbol', 'investments', 'changeToLiabilities',
       'totalCashflowsFromInvestingActivities', 'netBorrowings',
       'totalCashFromFinancingActivities', 'changeToOperatingActivities',
       'netIncome', 'changeInCash', 'beginPeriodCashFlow', 'endPeriodCashFlow',
       'totalCashFromOperatingActivities', 'issuanceOfCapitalStock',
       'depreciation', 'otherCashflowsFromInvestingActivities',
       'dividendsPaid', 'changeToInventory', 'changeToAccountReceivables',
       'salePurchaseOfStock', 'otherCashflowsFromFinancingActivities',
       'changeToNetincome', 'capitalExpenditures', 'changeReceivables',
       'cashFlowsOtherOperating', 'exchangeRateChanges',
       'cashAndCashEquivalentsChanges', 'changeInWorkingCapital',
       'stockBasedCompensation', 'otherNonCashItems', 'freeCashFlow'],
      dtype='object')

In [111]:
balance = ac.get_library('us.stocks.fundamental.balance')
balance.read('JPM.US').data

,filing_date,currency_symbol,totalAssets,intangibleAssets,earningAssets,otherCurrentAssets,totalLiab,totalStockholderEquity,deferredLongTermLiab,otherCurrentLiab,...,preferredStockRedeemable,capitalSurpluse,liabilitiesAndStockholdersEquity,cashAndShortTermInvestments,propertyPlantAndEquipmentGross,propertyPlantAndEquipmentNet,accumulatedDepreciation,netWorkingCapital,netInvestedCapital,commonStockSharesOutstanding
date,,,,,,,,,,,,,,,,,,,,,
1986-03-31,1986-03-31,USD,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,147943028.00
1987-03-31,1987-03-31,USD,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,152497751.00
1988-03-31,1988-03-31,USD,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,168596702.00
1989-03-31,1989-03-31,USD,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,193208396.00
1989-12-31,1989-12-31,USD,71513000000.00,None,None,None,67808000000.00,3705000000.00,None,None,...,None,None,71513000000.00,6866000000.00,1092000000.00,1092000000.00,None,None,None,345358321.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-06-30,2022-08-03,USD,3841314000000.00,8663000000.00,None,-972644000000.00,3555171000000.00,286143000000.00,None,-371748000000.00,...,None,88614000000.00,3841314000000.00,876167000000.00,None,26770000000.00,None,None,737830000000.00,2966300000.00
2022-09-30,2022-11-03,USD,3773884000000.00,9345000000.00,None,193216000000.00,3485866000000.00,288018000000.00,None,-347882000000.00,...,None,88865000000.00,3773884000000.00,3000000.00,None,27199000000.00,None,None,723694000000.00,2965400000.00
2022-12-31,2023-02-21,USD,3665743000000.00,9197000000.00,None,185369000000.00,3373411000000.00,292332000000.00,None,-344168000000.00,...,None,89044000000.00,3665743000000.00,773091000000.00,None,27734000000.00,None,None,731655000000.00,2967100000.00
2023-03-31,2023-05-03,USD,3744305000000.00,9946000000.00,None,195917000000.00,3441223000000.00,303082000000.00,None,-317318000000.00,...,None,89155000000.00,3744305000000.00,743248000000.00,None,28266000000.00,None,None,758561000000.00,2972700000.00
2023-06-30,2023-08-03,USD,3868240000000.00,11858000000.00,None,163563000000.00,3555724000000.00,312516000000.00,None,-327956000000.00,...,None,89578000000.00,3868240000000.00,698385000000.00,None,29493000000.00,None,None,822476000000.00,2948300000.00

In [112]:
balance.read('JPM.US').data.columns

Index(['filing_date', 'currency_symbol', 'totalAssets', 'intangibleAssets',
       'earningAssets', 'otherCurrentAssets', 'totalLiab',
       'totalStockholderEquity', 'deferredLongTermLiab', 'otherCurrentLiab',
       'commonStock', 'capitalStock', 'retainedEarnings', 'otherLiab',
       'goodWill', 'otherAssets', 'cash', 'cashAndEquivalents',
       'totalCurrentLiabilities', 'currentDeferredRevenue', 'netDebt',
       'shortTermDebt', 'shortLongTermDebt', 'shortLongTermDebtTotal',
       'otherStockholderEquity', 'propertyPlantEquipment',
       'totalCurrentAssets', 'longTermInvestments', 'netTangibleAssets',
       'shortTermInvestments', 'netReceivables', 'longTermDebt', 'inventory',
       'accountsPayable', 'totalPermanentEquity',
       'noncontrollingInterestInConsolidatedEntity',
       'temporaryEquityRedeemableNoncontrollingInterests',
       'accumulatedOtherComprehensiveIncome', 'additionalPaidInCapital',
       'commonStockTotalEquity', 'preferredStockTotalEquity',
       'retainedEarningsTotalEquity', 'treasuryStock',
       'accumulatedAmortization', 'nonCurrrentAssetsOther',
       'deferredLongTermAssetCharges', 'nonCurrentAssetsTotal',
       'capitalLeaseObligations', 'longTermDebtTotal',
       'nonCurrentLiabilitiesOther', 'nonCurrentLiabilitiesTotal',
       'negativeGoodwill', 'warrants', 'preferredStockRedeemable',
       'capitalSurpluse', 'liabilitiesAndStockholdersEquity',
       'cashAndShortTermInvestments', 'propertyPlantAndEquipmentGross',
       'propertyPlantAndEquipmentNet', 'accumulatedDepreciation',
       'netWorkingCapital', 'netInvestedCapital',
       'commonStockSharesOutstanding'],
      dtype='object')

In [114]:
insiders = ac.get_library('stocks.insidiers.us.stable')
insiders.read('JPM.US').data

,ownerCik,ownerName,transactionDate,transactionCode,transactionAmount,transactionPrice,transactionAcquiredDisposed,postTransactionAmount,secLink
date,,,,,,,,,
2022-10-03,None,Deirdre O'brien,2022-10-03,S,176299,142.16,D,136290,http://www.sec.gov/Archives/edgar/data/320193/...
2022-10-17,None,Deirdre O'brien,2022-10-17,S,8053,142.45,D,136290,http://www.sec.gov/Archives/edgar/data/320193/...
2022-10-28,None,Luca Maestri,2022-10-28,S,176299,155.95,D,110673,http://www.sec.gov/Archives/edgar/data/320193/...
2022-11-22,None,Chris Kondo,2022-11-22,S,20200,148.72,D,31505,http://www.sec.gov/Archives/edgar/data/320193/...
2023-03-22,None,Jeffrey E Williams,2023-03-22,S,187730,159.76,D,489816,http://www.sec.gov/Archives/edgar/data/320193/...
2023-04-03,None,Deirdre O'brien,2023-04-03,S,43622,165.41,D,136444,http://www.sec.gov/Archives/edgar/data/320193/...
2023-04-03,None,Timothy D Cook,2023-04-03,S,56072,165.17,D,3280052,http://www.sec.gov/Archives/edgar/data/320193/...
2023-04-04,None,Jeffrey E Williams,2023-04-04,S,77817,166.11,D,489816,http://www.sec.gov/Archives/edgar/data/320193/...
2023-04-06,None,Luca Maestri,2023-04-06,S,200,164.92,D,177657,http://www.sec.gov/Archives/edgar/data/320193/...
2023-04-13,None,Luca Maestri,2023-04-13,S,69996,165.25,D,107661,http://www.sec.gov/Archives/edgar/data/320193/...
2023-05-08,None,Chris Kondo,2023-05-08,S,4092,173.26,D,33946,http://www.sec.gov/Archives/edgar/data/320193/...
2023-08-07,None,Deirdre O'brien,2023-08-07,S,15419,178.56,D,136445,http://www.sec.gov/Archives/edgar/data/320193/...

In [116]:
holders = ac.get_library('stocks.holders.us.stable')
holders.read('JPM.US').data

,date,totalShares,totalAssets,currentShares,change,change_p
name,,,,,,
Vanguard Group Inc,2023-06-30,9.4096,0.9430,273451539,-1922011,-0.6980
BlackRock Inc,2023-03-31,6.6705,0.7451,193849295,-1077696,-0.5529
State Street Corporation,2023-03-31,4.2621,0.9108,123859046,-5878759,-4.5313
Vanguard Instl Ttl Stck Mkt Idx Tr,2023-03-31,3.1358,0.9580,91127627,1922946,2.1557
Vanguard Total Stock Mkt Idx Inv,2023-07-31,3.1318,1.0266,91011847,-97658,-0.1072
Vanguard 500 Index Investor,2023-07-31,2.4082,1.2006,69984077,405003,0.5821
Morgan Stanley - Brokerage Accounts,2023-06-30,2.1589,0.8993,62739902,2323678,3.8461
OFI Invest Asset Management,2023-03-31,1.9286,2.2238,56046201,56046201,0.0000
Bank of America Corp,2023-06-30,1.9219,0.8514,55851508,-5962072,-9.6452
"Geode Capital Management, LLC",2023-06-30,1.8364,0.9096,53367497,1057041,2.0207
FMR Inc,2023-03-31,1.4541,0.5037,42256822,-2551870,-5.6950
Capital Research & Mgmt Co - Division 3,2023-06-30,1.4137,1.4414,41082210,45927,0.1119
Capital World Investors,2023-06-30,1.3201,1.0731,38362149,-2178149,-5.3728
Wellington Management Company LLP,2023-06-30,1.3014,1.0427,37818621,583531,1.5672
"T. Rowe Price Associates, Inc.",2023-06-30,1.1400,0.6714,33128835,359312,1.0965
Fidelity® 500 Index,2023-06-30,1.1355,1.1411,32998956,176112,0.5366
Northern Trust Corp,2023-06-30,1.1086,0.9004,32218219,-999906,-3.0101
SPDR® S&P 500 ETF Trust,2023-08-30,1.1009,1.1471,31992295,-62712,-0.1956
Massachusetts Financial Services Company,2023-06-30,1.0806,1.4995,31402397,-439429,-1.3800
Bank of New York Mellon Corp,2023-06-30,1.0338,0.9172,30042826,-878317,-2.8405
iShares Core S&P 500 ETF,2023-08-30,0.9426,1.1437,27394012,-22750,-0.0830
Vanguard Value Index Inv,2023-07-31,0.8744,2.6256,25410999,146858,0.5813
Wells Fargo & Co,2023-06-30,0.8487,0.9897,24662927,-305361,-1.2230
Ameriprise Financial Inc,2023-03-31,0.7708,0.9571,22399560,-14997,-0.0669
Royal Bank of Canada,2023-06-30,0.7704,0.8542,22387961,817374,3.7893
Financial Select Sector SPDR® ETF,2023-08-30,0.7077,9.1568,20566681,133750,0.6546
Charles Schwab Investment Management Inc,2023-06-30,0.6919,0.8256,20107995,-95967,-0.4750
Legal & General Group PLC,2023-06-30,0.6857,0.9428,19926070,745061,3.8844
Vanguard Institutional Index I,2023-07-31,0.6831,1.2047,19852901,-95716,-0.4798
Vanguard Dividend Appreciation ETF,2023-07-31,0.5678,3.1121,16500256,-91126,-0.5492
MFS Large Cap Value Equity,2023-06-30,0.5609,4.0963,16301403,-151221,-0.9191
MFS Value A,2023-07-31,0.5577,4.3381,16207397,-94006,-0.5767
Capital Group Wash Mutual Invtrs Comp,2023-06-30,0.5276,1.4020,15333324,11179,0.0730
American Funds Washington Mutual A,2023-06-30,0.5276,1.4020,15333324,11179,0.0730
American Funds American Balanced A,2023-06-30,0.5236,1.0948,15216401,-64300,-0.4208
American Funds Income Fund of Amer A,2023-06-30,0.4781,1.7075,13893066,-154862,-1.1024
State St S&P 500® Indx SL Cl III,2023-07-31,0.4765,1.1910,13848796,-87556,-0.6283
Vanguard High Dividend Yield ETF,2023-07-31,0.4531,3.3043,13166795,-16126,-0.1223
Vanguard Equity-Income Inv,2023-06-30,0.3914,3.0700,11375674,-1213851,-9.6418
Blackrock Eq Idx Fund CF,2023-06-30,0.3628,1.1400,10543058,378750,3.7263

In [118]:
sentiment = ac.get_library('sentiment.stable')
sentiment.read('JPM.US').data

            count  normalized
date
2016-02-29      1      0.9980
2016-03-10      1      0.9990
2016-03-22      1      0.9980
2016-04-21      1      0.9980
2016-04-28      1      0.8810
...           ...         ...
2023-08-28      2      1.0000
2023-08-29      8      0.5603
2023-08-31      4      0.9703
2023-09-02      1      1.0000
2023-09-03      1      0.9990

[946 rows x 2 columns]

In [120]:
marketcap = ac.get_library('mktcap.stable')
marketcap.read('JPM.US').data

                   value
date
2018-08-31  385090100200
2018-09-07  384216270300
2018-09-14  381460345400
2018-09-21  396080191200
2018-09-28  379242161800
...                  ...
2023-08-09  446926858300
2023-08-16  436464951200
2023-08-23  428269790700
2023-08-30  430565598000
2023-09-01  426671443700

[262 rows x 1 columns]